stages:
  - staging
  - production

variables:
  SERVICE_DIRECTORY: /home/admin/b3-hyperion
  DOCKER_COMPOSE_COMMAND: docker-compose  -f docker-compose.prod.yml up -d --build
  VM_USER: admin

before_script:
  - apk update
  - apk add openssh-client bash sshpass
  - export GIT_DISCOVERY_ACROSS_FILESYSTEM=1
  
deploy_staging:
  stage: staging
  script:
    - sshpass -p $STAGING_VM_PASSWORD ssh -o StrictHostKeyChecking=no $VM_USER@$STAGING_VM_IP "cd $SERVICE_DIRECTORY ; echo "==PULLING LATEST MASTER==" ; git checkout master ; git pull origin master ; echo "==REBUILDING DOCKER IMAGE==" ; $DOCKER_COMPOSE_COMMAND"
  only:
    - master

deploy_production:
  stage: production
  script:
    - sshpass -p $PRODUCTION_VM_PASSWORD ssh -o StrictHostKeyChecking=no $VM_USER@$PRODUCTION_VM_IP "cd $SERVICE_DIRECTORY ; echo "==PULLING LATEST MASTER==" ; git checkout master ; git pull origin master ; echo "==REBUILDING DOCKER IMAGE==" ; $DOCKER_COMPOSE_COMMAND"
  only:
    - master
  when: manual
